# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
notifications:
  email: false

r_packages:
  - covr
  - devtools
  
install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  - tarball_script =
      '$version = $1 if (/^Version:\s(\S+)/);'\
      '$package = $1 if (/^Package:\s*(\S+)/);'\
      'END { print "${package}_$version.tar.gz" }'\
  - export 'PKG_TARBALL', "$(perl -ne '#{tarball_script}' DESCRIPTION)"
  - ls
  - echo $PKG_TARBALL
  
after_success:
  - travis_wait 60 Rscript -e 'library(covr); covr::codecov()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
