# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
notifications:
  email: false

r_packages:
  - covr
  - devtools
  
install:
- R -e 'devtools::install_deps(dep = T)'

script:
- R CMD build .
- travis_wait 60 R CMD check *tar.gz

after_success:
    - travis_wait 60 Rscript -e 'library(covr); covr::codecov()'
