# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

sudo: false
warnings_are_errors: true
cache: packages

r_packages:
  - covr
  - devtools
  - pkgdown

script:
  - set -e
  - R CMD build .
  - travis_wait 60 R CMD check --as-cran *tar.gz
  - export PKG_TARBALL="$(find *.tar.gz)"
  - echo $PKG_TARBALL
  - set +e

after_success:
  - travis_wait 60 Rscript -e 'library(covr); covr::codecov()'

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
